name: Go
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [ "1.18", "1.19", "1.20" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v3
      - name: build dot command
        run: go build -v cmd/dot/dot.go
      - name: test
        if: ${{ matrix.os != 'windows-latest' }}
        run: go test -race -v ./...
